from typing import Protocol

from napari.layers import Image
from napari.viewer import ViewerModel
from qtpy.QtWidgets import QLabel, QPushButton, QWidget


class ProcessWidgetAPI(Protocol):
    def new_image_open(
        self, image_tuple: tuple[Image, ...] | None, image_path: str | None
    ): ...
    def deleteLater(self): ...
    def parent(self) -> QWidget: ...


class ScoreWidgetAPI(Protocol):
    def get_image_path_list(self) -> list[str]: ...
    def deleteLater(self): ...
    def parent(self) -> QWidget: ...


class PrepareWidgetAPI(Protocol):
    def deleteLaber(self): ...
    def parent(self) -> QWidget: ...


class SummaryWidgetAPI(Protocol):
    def deleteLater(self): ...
    def parent(self) -> QWidget: ...


class MainWidgetCallBacks(Protocol):
    def set_process_widget(
        self, setting_widget: ProcessWidgetAPI, widget_name: str
    ): ...
    def get_process_control_images_and_paths(
        self,
    ) -> tuple[str, str, list[Image]] | None: ...
    def get_process_control_tiles(
        self,
    ) -> dict[int, str]: ...
    def open_process_control_tile_images(
        self, tile_index: int
    ) -> list[Image] | None: ...
    def close_process_control_tile_images(self) -> None: ...
    def get_process_widget(self) -> ProcessWidgetAPI | None: ...
    def validate_process_results(self, image_path: str) -> None: ...
    def set_score_widget(
        self, setting_widget: ScoreWidgetAPI, widget_name: str
    ) -> None: ...
    def get_score_widget(self) -> QWidget | None: ...
    def set_prepare_widget(
        self, setting_widget: PrepareWidgetAPI, widget_name: str
    ): ...
    def get_prepare_widget(self) -> PrepareWidgetAPI | None: ...


class CToolButton(Protocol):
    _button: QPushButton
    _button_text: str
    _launched_widget: QWidget | None
    _widget_name: str
    _status_label: QLabel | None

    def __init__(
        self, napari_viewer: "ViewerModel", main_widget: MainWidgetCallBacks
    ) -> None: ...

    def get_button(self) -> QWidget: ...
    def get_status_label(self) -> QLabel | None: ...
    def deactivate_buttons(self) -> None: ...
    def activate_buttons(self) -> None: ...
    def launch_widget(self) -> QWidget | None: ...
    def set_status_label_state(self, state: bool) -> None: ...
    def validate_property(self, image_path: str) -> None: ...


class ScoreWidgetButtonAPI(CToolButton):
    def get_blind_checkbox_state(self) -> bool: ...
    def get_shuffle_checkbox_state(self) -> bool: ...
